language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn test

notifications:
  recipients:
    - lalo.diaz1896@gmail.com
  on_success: always
  on_failure: always

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 5b73a159-401f-46ad-8fbe-5bc73757277c
  app: platzi-store-backend-test
  on:
    repo: eduardoGao/platzi-store-backend

